In [405]:
from Bio import SeqIO
from pathlib import Path
import os
import pandas as pd
import parse_fasta as pf

Process proteins per phage into dataframe

In [406]:
base_path = Path("../data")

proteins_path = base_path / "proteins"

data = []
for file in proteins_path.iterdir():
    for record in pf.parse_fasta(file):
        data.append([file.stem, record.id, str(record.seq), record.description])

data_df = pd.DataFrame(
    data, columns=["phage_id", "protein_id", "sequence", "description"]
)

print("Total proteins: ", len(data_df), "\n\n")
data_df.head()

Total proteins:  15889

,phage_id,protein_id,sequence,description
0,MZ501058,QXV77207.1,MANDVLVPDLMSPEGMDVIEAYLQCGSDVPSAARSLGMSGIAFRDI...,terminase small subunit
1,MZ501058,QXV77208.1,MEVSRPYVNTVDVIDFGIDKRFFRLPVSGILAQEGITPNGPQIAII...,terminase large subunit
2,MZ501058,QXV77209.1,MASNIKYKRDAISLMRDGIKSQYKKDSQCAICGCAEELELHHYHTV...,nicking endonuclease
3,MZ501058,QXV77210.1,MGFKSWITEKLNPGQRIIRDMEPVSHRTNRKPFTTGQAYNKIEILN...,portal protein
4,MZ501058,QXV77211.1,MIDYNGLKTIFGEKLPESHIFFATVAAHKYVPSYAFLRRELGLSSA...,head decoration protein

Write proteins to fasta

In [ ]:
fasta_file = "../data/interpro/interpro_sequences.fasta"
with open(fasta_file, "w") as outfile:
    for index, row in data_df.iterrows():
        protein_id = row["protein_id"]
        sequence = row["sequence"]
        outfile.write(f">{protein_id}\n{sequence}\n")

data_df[["protein_id", "sequence"]].to_csv(
    "../data/protein_sequences.tsv", sep="\t", index=False
)

Run Interproscan: ./interproscan.sh -i data/interpro/interpro_sequences.fasta -b data/interpro/

Load interproscan results

In [408]:
interpro_path = "../data/interpro/interpro.tsv"

interpro_df = pd.read_csv(interpro_path, sep="\t", header=None)

column_names = [
    "protein_name",
    "Sequence MD5 Digest",
    "Sequence Length",
    "Analysis",
    "Signature Accession",
    "Signature Description",
    "Start Location",
    "Stop Location",
    "Score",
    "Status",
    "Date",
    "accession",
    "InterPro Annotation Description",
    "GO Annotations",
    "Pathways annotations",
]

interpro_df.columns = column_names
interpro_df.head()

,protein_name,Sequence MD5 Digest,Sequence Length,Analysis,Signature Accession,Signature Description,Start Location,Stop Location,Score,Status,Date,accession,InterPro Annotation Description,GO Annotations,Pathways annotations
0,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,Pfam,PF06941,"5' nucleotidase, deoxy (Pyrimidine), cytosolic...",1,175,0.027,T,08-07-2025,IPR010708,5'(3')-deoxyribonucleotidase,-,-
1,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,Gene3D,G3DSA:3.40.50.1000,-,61,197,9.7E-15,T,08-07-2025,IPR023214,HAD superfamily,-,-
2,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,SUPERFAMILY,SSF56784,HAD-like,2,194,3.35E-10,T,08-07-2025,IPR036412,HAD-like superfamily,-,-
3,XPK40590.1,8e26baa52b47ccc2f037749e8fd2cc21,635,Pfam,PF12708,"Rhamnogalacturonase A/epimerase, pectate lyase...",162,350,0.0018,T,08-07-2025,IPR024535,"Rhamnogalacturonase A/B/Epimerase-like, pectat...",-,-
4,XPK40590.1,8e26baa52b47ccc2f037749e8fd2cc21,635,Gene3D,G3DSA:2.160.20.10,-,133,480,2.0E-18,T,08-07-2025,IPR012334,Pectin lyase fold,-,-

In [409]:
# Clean dataframe
print("Before: ", len(interpro_df), " entries")

interpro_df = interpro_df[["protein_name", "accession"]].drop_duplicates()

interpro_df.reset_index(drop=True, inplace=True)

interpro_df = interpro_df.replace("-", pd.NA).dropna()

print("After: ", len(interpro_df), " entries")
interpro_df.head()

Before:  30190  entries
After:  15136  entries

  protein_name  accession
0   QXV79977.1  IPR010708
1   QXV79977.1  IPR023214
2   QXV79977.1  IPR036412
3   XPK40590.1  IPR024535
4   XPK40590.1  IPR012334

Cluster based on interpro accessions

In [410]:
unique_accessions = (
    interpro_df.groupby("accession")["protein_name"].apply(list).reset_index()
)

unique_accessions.head()

   accession                                       protein_name
0  IPR000064  [QXV81853.1, XPK41671.1, QXV76156.1, QXV80787....
1  IPR000086  [QXV84970.1, QXV78675.1, QXV78955.1, QXV83268....
2  IPR000189  [XPK40951.1, XPK43261.1, XPK42576.1, XPK42676....
3  IPR000212               [QXV81426.1, QXV78209.1, QXV83817.1]
4  IPR000305  [NP_049645.1, QXV76220.1, QXV84747.1, NP_04969...

In [411]:
len(unique_accessions["protein_name"][0])

28

# Potential binary vector for interpro signatures here

In [412]:
# ...

Load Interpro to GO list

In [413]:
ip2go = []
with open("../data/interpro/interpro2go", "r") as index:
    for row in index:
        row = row.strip()

        if row.startswith("!"):
            continue

        items = row.split("InterPro:")[1].split(" > ")

        ip_accession = items[0].split(" ")[0]
        ip_term = " ".join(items[0].split(" ")[1:])

        go_items = items[1].split(";")
        go_term = go_items[0].strip().replace("GO:", "")
        go_accession = go_items[1].strip()

        ip2go.append([ip_accession, ip_term, go_accession, go_term])

ip2go_df = pd.DataFrame(
    ip2go,
    columns=[
        "Interpro accession",
        "Interpro description",
        "GO accession",
        "GO description",
    ],
)
ip2go_df.head()

,Interpro accession,Interpro description,GO accession,GO description
0,IPR000003,Retinoid X receptor/HNF4,GO:0003677,DNA binding
1,IPR000003,Retinoid X receptor/HNF4,GO:0003707,nuclear steroid receptor activity
2,IPR000003,Retinoid X receptor/HNF4,GO:0008270,zinc ion binding
3,IPR000003,Retinoid X receptor/HNF4,GO:0006355,regulation of DNA-templated transcription
4,IPR000003,Retinoid X receptor/HNF4,GO:0005634,nucleus

#### Assign GO-terms to proteins

Add root Go-term to all GO-terms

In [414]:
import obonet

graph = obonet.read_obo("../data/interpro/go-basic.obo")

# Create a mapping dict: GO ID -> namespace
go_to_namespace = {
    go_id: data.get("namespace") for go_id, data in graph.nodes(data=True)
}

# Map it to your dataframe
ip2go_df["namespace"] = ip2go_df["GO accession"].map(go_to_namespace)
ip2go_df.head(10)

,Interpro accession,Interpro description,GO accession,GO description,namespace
0,IPR000003,Retinoid X receptor/HNF4,GO:0003677,DNA binding,molecular_function
1,IPR000003,Retinoid X receptor/HNF4,GO:0003707,nuclear steroid receptor activity,molecular_function
2,IPR000003,Retinoid X receptor/HNF4,GO:0008270,zinc ion binding,molecular_function
3,IPR000003,Retinoid X receptor/HNF4,GO:0006355,regulation of DNA-templated transcription,biological_process
4,IPR000003,Retinoid X receptor/HNF4,GO:0005634,nucleus,cellular_component
5,IPR000006,"Metallothionein, vertebrate",GO:0046872,metal ion binding,molecular_function
6,IPR000009,Protein phosphatase 2A regulatory subunit PR55,GO:0019888,protein phosphatase regulator activity,molecular_function
7,IPR000009,Protein phosphatase 2A regulatory subunit PR55,GO:0000159,protein phosphatase type 2A complex,cellular_component
8,IPR000010,Cystatin domain,GO:0004869,cysteine-type endopeptidase inhibitor activity,molecular_function
9,IPR000011,Ubiquitin/SUMO-activating enzyme E1-like,GO:0008641,ubiquitin-like modifier activating enzyme acti...,molecular_function

Cluster GO accessions for Interpro accessions

In [415]:
ip2go_grouped = ip2go_df.groupby("Interpro accession")["GO accession"].apply(list)

ip2go_grouped.head()

Interpro accession
IPR000003    [GO:0003677, GO:0003707, GO:0008270, GO:000635...
IPR000006                                         [GO:0046872]
IPR000009                             [GO:0019888, GO:0000159]
IPR000010                                         [GO:0004869]
IPR000011                             [GO:0008641, GO:0036211]
Name: GO accession, dtype: object

In [416]:
unique_accessions["GO accessions"] = unique_accessions["accession"].map(ip2go_grouped)
unique_accessions.dropna(inplace=True)
unique_accessions.reset_index(drop=True, inplace=True)
unique_accessions.head()

,accession,protein_name,GO accessions
0,IPR000189,"[XPK40951.1, XPK43261.1, XPK42576.1, XPK42676....","[GO:0008933, GO:0000270, GO:0016020]"
1,IPR000212,"[QXV81426.1, QXV78209.1, QXV83817.1]","[GO:0003677, GO:0003678, GO:0005524]"
2,IPR000330,"[QXV81953.1, XPK40988.1, QXV83003.1, QXV85044....","[GO:0005524, GO:0140658]"
3,IPR000358,"[QXV81755.1, QXV84799.1, QXV85131.1, QXV78773....",[GO:0009263]
4,IPR000398,"[QXV82049.1, QXV75921.1, QXV75344.1, QXV85905....","[GO:0004799, GO:0006231]"

Add namespaces

In [417]:
namespaces_grouped = (
    ip2go_df.dropna(subset=["namespace"])
    .groupby("Interpro accession")["namespace"]
    .apply(
        lambda x: list(set(x))[0]
    )  # Only select the first namespace, the order of appearance is cc -> mf -> bf
)

unique_accessions["namespace"] = unique_accessions["accession"].map(namespaces_grouped)
unique_accessions.head()

,accession,protein_name,GO accessions,namespace
0,IPR000189,"[XPK40951.1, XPK43261.1, XPK42576.1, XPK42676....","[GO:0008933, GO:0000270, GO:0016020]",cellular_component
1,IPR000212,"[QXV81426.1, QXV78209.1, QXV83817.1]","[GO:0003677, GO:0003678, GO:0005524]",molecular_function
2,IPR000330,"[QXV81953.1, XPK40988.1, QXV83003.1, QXV85044....","[GO:0005524, GO:0140658]",molecular_function
3,IPR000358,"[QXV81755.1, QXV84799.1, QXV85131.1, QXV78773....",[GO:0009263],biological_process
4,IPR000398,"[QXV82049.1, QXV75921.1, QXV75344.1, QXV85905....","[GO:0004799, GO:0006231]",molecular_function

Explode by protein_name

In [419]:
namespace_df = unique_accessions.explode("protein_name").reset_index(drop=True)
namespace_df = namespace_df[["protein_name", "namespace"]].dropna()
namespace_df

     protein_name           namespace
0      XPK40951.1  cellular_component
1      XPK43261.1  cellular_component
2      XPK42576.1  cellular_component
3      XPK42676.1  cellular_component
4      XPK40276.1  cellular_component
...           ...                 ...
4055   QXV80513.1  molecular_function
4056   QXV80335.1  molecular_function
4057   QXV77353.1  molecular_function
4058   QXV80160.1  molecular_function
4059   QXV84713.1  molecular_function

[4044 rows x 2 columns]